export const PENDING_TXT = "YOUR PROFILE IS IN PENDING STATE";
export const INITATE_TXT =
  "PLEASE COMPLETE YOUR PAYMENT OF INR 100 AND UPDATE TRANSITION ID FOR VERIFICATION";
export const REJECTED_TXT = "YOUR PROFILE HAS BEEN REJECTED";
export const APPROVED_TXT = "YOUR PROFILE HAS BEEN APPROVED 🎉";
export const BLOCKED_TXT = "YOUR PROFILE HAS BEEN BLOCKED";

